artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  data_path: artifacts/data_ingestion/customer_seg.csv
  mongodb_url: mongodb+srv://datascience:<password>@cluster0.4vt0cq9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  DATABASE_NAME: Intership
  COLLECTION_NAME: customer_segmentation

data_validation: 
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/customer_seg.csv
  status_file: artifacts/data_validation/status.txt

data_transformation: 
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/customer_seg.csv
  train_data_path: artifacts/data_transformation/train_data.csv
  test_data_path: artifacts/data_transformation/test_data.csv
  train_data_scaled_path: artifacts/data_transformation/train_scaled.csv
  test_data_scaled_path: artifacts/data_transformation/test_scaled.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl


model_trainer: 
  root_dir: artifacts/model_trainer
  train_data_scaled_path: artifacts/data_transformation/train_scaled.csv
  test_data_scaled_path: artifacts/data_transformation/test_scaled.csv
  train_data_not_scaled: artifacts/data_transformation/train_data.csv
  test_data_not_scaled: artifacts/data_transformation/test_data.csv
  best_model_path: artifacts/model_trainer/best_Model.h5
  dim_red_model_path: artifacts/model_trainer/dim_red.h5


  
   