artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  data_path: artifacts/data_ingestion/customer_seg.csv
  mongodb_url: mongodb+srv://datascience:datascience@cluster0.4vt0cq9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  DATABASE_NAME: Intership
  COLLECTION_NAME: customer_segmentation

data_validation: 
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/customer_seg.csv
  status_file: artifacts/data_validation/status.txt

data_transformation: 
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/customer_seg.csv
  train_data_path: artifacts/data_transformation/train_data.csv
  test_data_path: artifacts/data_transformation/test_data.csv
  train_data_scaled_path: artifacts/data_transformation/train_scaled.csv
  test_data_scaled_path: artifacts/data_transformation/test_scaled.csv
